// <auto-generated />
namespace Application1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updateduserandvehiclemodelsaswellastheircontrollers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateduserandvehiclemodelsaswellastheircontrollers));
        
        string IMigrationMetadata.Id
        {
            get { return "201806221543261_updated user and vehicle models as well as their controllers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
